import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../../Components/Navbar";
import CustomCarousel from "../../Components/CustomCarousel";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  // title: "Manish Basnet - Frontend Developer",
  // description: "Generated by create next app",
  metadataBase: new URL('https://www.manishbasnet.com'),
  title:{
    default:'Manish Basnet - Frontend Developer',
    template:'%s - Manish'
  },
  description:'Explore our pioneering projects, dynamic solutions, and unparalleled expertise in software development, web design, and digital transformation.',
  // , driving innovation and excellence in the digital space
  twitter: {
    card:'summary_large_image'
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <CustomCarousel />

        {/* <Suspense fallback={<Loading />}> */}
          {children}
        {/* </Suspense> */}
      </body>
    </html>
  );
}
